language: python
python:
- '2.7'

sudo: required
before_install:
- jdk_switcher use oraclejdk8

script:
- TERM=dumb ./build-support/jenkins/build.sh

cache:
  directories:
  - ${HOME}/.cache/pants
  - ${HOME}/.gradle
  - ${HOME}/.npm

